import assert from 'node:assert/strict';
import {ObjectId} from 'mongodb';
const databaseName = `tw_flow_test_${new ObjectId().toHexString()}`;
process.env.MONGODB_DB_NAME = databaseName;
const {connectDB,closeDB}=await import('./src/config/db.js');
const farmer=await import('./src/services/farmer.service.js');
const {updateFarmerApprovalService:decide}=await import('./src/services/auth.service.js');
const support=await import('./src/services/support.service.js');
const {db}=await connectDB();
assert.equal(db.databaseName,databaseName);
const uid=new ObjectId(),adminId=new ObjectId(),venueId=new ObjectId();
const owner={id:String(uid),name:'Isolated test farmer',role:'farmer'},admin={id:String(adminId),name:'Isolated test admin',role:'admin'};
try {
 await db.collection('users').insertOne({_id:uid,firstName:'Test',lastName:'Farmer',phone:'123456789',role:'farmer'});
 const application=await farmer.getFarmerOnboardingService(String(uid));
 await assert.rejects(decide(application.farmerProfileId,'approved',String(adminId)),{statusCode:409});
 await db.collection('markets').insertOne({_id:venueId,countryCode:'GB',city:'London',isActive:true});
 const steps=[ [1,{contactPerson:'Test Farmer',phone:'123456789'}], [2,{countryCode:'GB',countryName:'United Kingdom',region:'England',city:'London',address:'10 Test Road',coordinates:{latitude:51.5,longitude:-0.1}}], [3,{businessName:'Test Farm',bio:'Isolated test application farm'}], [4,{requestedMarketIds:[String(venueId)]}], [8,{agreedToTerms:true}] ];
 for(const [step,data] of steps)await farmer.saveFarmerOnboardingStepService(String(uid),{step,data});
 assert.equal((await farmer.submitFarmerOnboardingService(String(uid))).status,'submitted');
 await assert.rejects(farmer.saveFarmerOnboardingStepService(String(uid),{step:1,data:steps[0][1]}),{statusCode:409});
 await assert.rejects(decide(application.farmerProfileId,'rejected',String(adminId)),{statusCode:400});
 await decide(application.farmerProfileId,'rejected',String(adminId),'Please clarify your farm description.');
 let state=await farmer.getFarmerOnboardingService(String(uid));assert.equal(state.status,'rejected');assert.match(state.adminNotes,/clarify/);
 await farmer.saveFarmerOnboardingStepService(String(uid),{step:3,data:{...steps[2][1],bio:'Updated isolated farm description for review'}});
 await farmer.submitFarmerOnboardingService(String(uid));
 await decide(application.farmerProfileId,'approved',String(adminId));
 state=await farmer.getFarmerOnboardingService(String(uid));assert.equal(state.status,'approved');assert.equal(state.approvalStatus,'approved');
 const ticket=await support.createTicket(owner,{subject:'Application support',message:'Please help with my market application.'});
 assert.equal((await support.listTickets(admin,ticket.reference)).length,1);
 await assert.rejects(support.getTicket({...owner,id:String(new ObjectId())},ticket.id),{statusCode:404});
 await support.replyTicket(admin,ticket.id,{message:'Your application has now been reviewed.'});
 assert.equal((await support.getTicket(owner,ticket.id)).messages.length,2);
 await support.closeTicket(admin,ticket.id);
 await assert.rejects(support.replyTicket(owner,ticket.id,{message:'Another reply'}),{statusCode:409});
 const cid=new ObjectId();await db.collection('conversations').insertOne({_id:cid});await db.collection('messages').insertOne({conversationId:cid,text:'Isolated support evidence',senderRole:'customer',createdAt:new Date()});
 assert.equal((await support.inspectConversation(admin,String(cid))).messages[0].text,'Isolated support evidence');
 assert.equal(await db.collection('auditLogs').countDocuments({action:'SUPPORT_CONVERSATION_VIEW'}),1);
 const participation=await import('./src/services/marketParticipation.service.js');
 const secondVenue=new ObjectId(),wrongVenue=new ObjectId();
 await db.collection('markets').insertMany([{_id:secondVenue,name:'Second test venue',countryCode:'GB',city:'London',isActive:true},{_id:wrongVenue,name:'Wrong city',countryCode:'PK',city:'Lahore',isActive:true}]);
 await assert.rejects(participation.requestMarket(application.farmerProfileId,String(wrongVenue)),{statusCode:400});
 await participation.requestMarket(application.farmerProfileId,String(secondVenue));
 await assert.rejects(participation.requestMarket(application.farmerProfileId,String(secondVenue)),{statusCode:409});
 await assert.rejects(participation.decideMarket(application.farmerProfileId,String(secondVenue),'rejected','',String(adminId)),{statusCode:400});
 await participation.decideMarket(application.farmerProfileId,String(secondVenue),'rejected','Please confirm attendance.',String(adminId));
 await participation.requestMarket(application.farmerProfileId,String(secondVenue));
 await participation.decideMarket(application.farmerProfileId,String(secondVenue),'approved','',String(adminId));
 assert.ok((await db.collection('farmerProfiles').findOne({_id:new ObjectId(application.farmerProfileId)})).marketIds.some(id=>id.equals(secondVenue)));
 await assert.rejects(participation.decideMarket(application.farmerProfileId,String(secondVenue),'approved','',String(adminId)),{statusCode:409});
 const categoryId=new ObjectId();await db.collection('categories').insertOne({_id:categoryId,name:'Test vegetables',isActive:true});
 const {createFarmerProductService}=await import('./src/services/product.service.js');
 await assert.rejects(createFarmerProductService(application.farmerProfileId,{name:'Test produce',categoryId:'not-a-category'}),{statusCode:400});
 const product=await createFarmerProductService(application.farmerProfileId,{name:'Test produce',categoryId:String(categoryId),unit:'kg',basePriceMinor:200,currency:'GBP'});
 assert.equal(await db.collection('stockOffers').countDocuments({productId:new ObjectId(product.id)}),0);
 const {createPickupWindowService}=await import('./src/services/inventory.service.js');
 await assert.rejects(createPickupWindowService(application.farmerProfileId,{marketId:String(wrongVenue)}),{statusCode:403});
 console.log('PASS: Venue approval lifecycle, wrong-city/duplicate protection, category validation, no invented stock and unapproved pickup blocked.');
 console.log('PASS: Real MongoDB draft/submission/rejection/resubmission/approval, ticket ownership/reply/closure and audited chat lookup.');
} finally {
 assert.equal(db.databaseName,databaseName);
 assert.match(databaseName,/^tw_flow_test_[a-f0-9]{24}$/);
 await db.dropDatabase();
 await closeDB();
 console.log('Isolated test database removed; application database untouched.');
}

