import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Search,ArrowUpRight,MapPin,Users,ClipboardList} from 'lucide-react';
import {useMarket} from '../components/ui';
import {activeOrder,date} from '../data/market';
export function AdminOperations(){
 const s=useMarket();const [country,setCountry]=useState(''),[search,setSearch]=useState('');
 const countries=[...new Set(s.markets.map(m=>m.countryCode).filter(Boolean))];
 const markets=s.markets.filter(m=>(!country||m.countryCode===country)&&`${m.name} ${m.city}`.toLowerCase().includes(search.toLowerCase()));
 const waiting=s.farmers.filter(f=>f.onboardingStatus==='submitted'&&f.state==='Pending'&&(!country||f.countryCode===country));
 return <section className="admin-operations"><div className="admin-command-toolbar"><div><h2>Operations desk</h2><p>Real venue activity and applications ready for a decision.</p></div><div className="admin-command-filters"><label><Search size={16}/><span className="visually-hidden">Search markets</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search market or city"/></label><label><span className="visually-hidden">Country filter</span><select value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{countries.map(c=><option key={c} value={c}>{s.markets.find(m=>m.countryCode===c)?.countryName||c}</option>)}</select></label></div></div><div className="admin-operations-grid"><section className="admin-market-ledger"><header><h3><MapPin size={17}/> Market network</h3><span>{markets.length} venues</span></header><div className="admin-ledger-scroll"><table><thead><tr><th>Market / city</th><th>Next market day</th><th>Open reservations</th><th>Status</th><th><span className="visually-hidden">Manage</span></th></tr></thead><tbody>{markets.map(m=><tr key={m.id}><td><strong>{m.name}</strong><span>{m.city}, {m.countryName||m.countryCode}</span></td><td>{m.day?date(m.day):'Not scheduled'}</td><td>{s.orders.filter(o=>o.marketId===m.id&&activeOrder(o)).length}</td><td><span className={`admin-state ${m.active?'active':'paused'}`}>{m.active?'Active':'Paused'}</span></td><td><Link to={`/admin/markets/${m.id}/edit`} aria-label={`Manage ${m.name}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table>{!markets.length&&<p className="admin-empty">No markets match these filters.</p>}</div></section><aside className="admin-review-desk"><header><h3><ClipboardList size={17}/> Ready for review</h3><span>{waiting.length}</span></header>{waiting.slice(0,5).map(f=><Link className="admin-review-person" key={f.id} to={`/admin/farmers/${f.id}`}><span className="admin-person-mark"><Users size={18}/></span><div><strong>{f.name}</strong><span>{f.city||'Location in application'} · Submitted</span></div><ArrowUpRight size={16}/></Link>)}{!waiting.length&&<div className="admin-empty"><ClipboardList size={28}/><h4>No submitted applications waiting</h4><p>Incomplete drafts stay with the farmer until they submit.</p></div>}<Link className="admin-review-all" to="/admin/farmers">Open farmer management <ArrowUpRight size={16}/></Link><Link className="admin-review-all" to="/admin/support">Open support conversations <ArrowUpRight size={16}/></Link></aside></div></section>
}

