import {MarketRequestReview} from './FarmerMarkets';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {fetchAdminFarmersApi,updateFarmerApprovalStatusApi} from '../data/api';
import {gateway} from '../data/gateway';
import {LocationPicker} from '../components/LocationPicker';
function Details({data}:{data:Record<string,any>}){return <dl className="definition-list">{Object.entries(data).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1').replace(/_/g,' ')}</dt><dd>{v&&typeof v==='object'?Array.isArray(v)?v.join(', '):<Details data={v}/>:String(v??'—')}</dd></div>)}</dl>}
export function ApplicationReview({id}:{id:string}){
 const [f,setFarmer]=useState<any>(null),[error,setError]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const farmers=await fetchAdminFarmersApi();const found=farmers.find(f=>f.id===id);if(!found)throw Error('Application not found.');setFarmer(found)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[id]);
 async function decide(status:'approved'|'rejected'|'suspended'){if(status!=='approved'&&!reason.trim()){setError('Enter a reason the farmer can act on.');return}if(!window.confirm(`${status==='approved'?'Approve':status==='rejected'?'Return for changes':'Suspend'} this application?`))return;setBusy(true);setError('');try{await updateFarmerApprovalStatusApi(id,status,reason);await load();await gateway.refresh()}catch(e){setError(e instanceof Error?e.message:'Decision could not be saved.')}finally{setBusy(false)}}
 const steps=f?.onboarding?.stepData||{},point=steps.step2_location?.coordinates;
 return <div className="container section application-review"><Link to="/admin/farmers">Back to farmer applications</Link><h1>{f?.businessName||'Application review'}</h1>{error&&<p role="alert" className="error">{error}</p>}{f&&<><p>{f.approvalStatus} · {f.onboardingStatus==='submitted'?'Submitted for review':'Application '+f.onboardingStatus.replaceAll('_',' ')}</p><div className="paper-panel"><h2>Account details</h2><Details data={{contact:f.contactPerson,email:f.email,phone:f.phone,address:f.address,country:f.countryName,city:f.city}}/></div>{Object.entries(steps).map(([key,data])=><section className="paper-panel" key={key}><h2>{key.replace(/step(\d)_/,'Step $1 · ').replace(/_/g,' ')}</h2><Details data={data as Record<string,any>}/></section>)}{point&&<LocationPicker value={point} readOnly/>}<MarketRequestReview farmerId={id}/><section className="paper-panel"><h2>Review decision</h2>{f.adminNotes&&<p>Previous message: {f.adminNotes}</p>}<label>Message to farmer (required for return or suspension)<textarea rows={4} maxLength={250} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what needs correcting, or why the account is suspended."/></label><div className="actions"><button className="button" disabled={busy||!(f.onboardingStatus==='submitted'||f.approvalStatus==='suspended')} onClick={()=>void decide('approved')}>Approve farmer</button><button className="button secondary" disabled={busy||f.onboardingStatus!=='submitted'} onClick={()=>void decide('rejected')}>Return for changes</button>{f.approvalStatus==='approved'&&<button className="button secondary" disabled={busy} onClick={()=>void decide('suspended')}>Suspend account</button>}</div>{f.onboardingStatus!=='submitted'&&f.approvalStatus!=='suspended'&&f.approvalStatus!=='approved'&&<p>The farmer must finish and submit the application before you can approve it.</p>}</section></>}</div>
}
