import {useState,type FormEvent} from 'react';
import {Link,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,Check,Eye,EyeOff,Leaf,ShieldCheck,Mail} from 'lucide-react';
import {beginRegistrationApi,verifyRegistrationApi,sendLoginOtpApi,verifyLoginOtpApi,forgotPasswordApi,resetPasswordApi} from '../data/api';
import {gateway} from '../data/gateway';
import './auth-experience.css';
const rules=[['12 or more characters',(v:string)=>v.length>=12],['Uppercase & lowercase',(v:string)=>/[a-z]/.test(v)&&/[A-Z]/.test(v)],['At least one number',(v:string)=>/\d/.test(v)],['At least one symbol',(v:string)=>/[^a-zA-Z0-9]/.test(v)]] as const;
export const isStrongPassword=(v:string)=>rules.every(([,test])=>test(v))&&new TextEncoder().encode(v).length<=72;
export function PasswordField({value,onChange,strong=false,label='Password'}:{value:string;onChange:(v:string)=>void;strong?:boolean;label?:string}){
 const [show,setShow]=useState(false);const score=rules.filter(([,test])=>test(value)).length;
 return <div className="auth-password"><label>{label}<span className="auth-password-input"><input required name="password" type={show?'text':'password'} autoComplete={strong?'new-password':'current-password'} minLength={strong?12:1} value={value} onChange={e=>onChange(e.target.value)}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>{strong&&<><div className="password-strength" aria-label={`${score} of 4 password requirements met`}>{rules.map(([name],i)=><i key={name} className={score>i?'met':''}/>)}</div><ul className="password-rules">{rules.map(([name,test])=><li key={name} className={test(value)?'met':''}><Check size={13}/>{name}</li>)}</ul></>}</div>
}
export function AuthPage(){
 const {pathname}=useLocation();const navigate=useNavigate();const [params]=useSearchParams();const registering=pathname.startsWith('/register'),choosing=pathname==='/register',farmer=pathname.endsWith('/farmer');
 const [step,setStep]=useState<'form'|'verify'|'forgot'|'reset'|'done'>('form'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function enter(role:string){await gateway.signIn();const next=params.get('next');navigate(next&&next.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')&&(next===`/${role}`||next.startsWith(`/${role}/`)||role==='customer'&&/^\/(farmers|products|markets)\//.test(next))?next:`/${role}`)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const fields=new FormData(e.currentTarget);try{
 if(step==='forgot'){await forgotPasswordApi(email);setStep('reset');setPassword('');setConfirm('');return}
 if(step==='reset'){if(!isStrongPassword(password))throw Error('Meet all password requirements (maximum 72 bytes).');if(password!==confirm)throw Error('Passwords do not match.');await resetPasswordApi(email,code,password);setStep('done');setPassword('');setConfirm('');return}
 if(step==='verify'){const user=registering?await verifyRegistrationApi(challenge,code):await verifyLoginOtpApi(email,code);await enter(user.role);return}
 if(registering){if(!isStrongPassword(password))throw Error('Meet all password requirements (maximum 72 bytes).');if(password!==confirm)throw Error('Passwords do not match.');const data={name:String(fields.get('name')||''),email:email.trim(),password,phone:String(fields.get('phone')||''),address:String(fields.get('address')||''),...(farmer?{businessName:String(fields.get('businessName')||''),contactPerson:String(fields.get('name')||''),bio:''}:{})};const result=await beginRegistrationApi(farmer?'farmer':'customer',data);setChallenge(result.challengeId);setEmail(result.email);setPassword('');setConfirm('');setStep('verify');return}
 const result=await sendLoginOtpApi(email.trim(),password);if(result.user&&!result.otpSent){await enter(result.user.role)}else{setStep('verify')}
 }catch(e){setError(e instanceof Error?e.message:'Could not complete this request. Please try again.')}finally{setBusy(false)}}
 const title=step==='verify'?'Check your inbox.':step==='forgot'?'Let’s get you back in.':step==='reset'?'A fresh start.':step==='done'?'Password updated.':registering?(choosing?'Find your place at the market.':farmer?'Bring your harvest.':'Your next market day starts here.'):'Good to see you again.';
 return <div className="auth-experience"><aside className="auth-editorial"><Link to="/" className="auth-wordmark"><Leaf size={25}/> Gather & Grow</Link><div><span>The living market</span><h2>Good food.<br/>Real people.<br/>Closer together.</h2><p>Discover local produce, meet the growers and collect fresh food at your market.</p></div><ul><li><Check size={18}/> Reserve online, pay at pickup</li><li><Check size={18}/> Choose your market and collection time</li><li><Check size={18}/> Stay connected with your grower</li></ul></aside><main className="auth-surface"><div className="auth-form-wrap"><Link className="auth-back" to="/">← Back to the market</Link><div className="auth-step-label"><ShieldCheck size={17}/>{step==='verify'?'Email verification':registering?'Create your account':'Your market account'}</div><h1>{title}</h1><p className="auth-intro">{step==='verify'?`Enter the six-digit code sent to ${email}. It expires in 10 minutes.`:step==='forgot'?'Use the email you registered with. We’ll email you a reset code.':step==='reset'?'Enter the code from your inbox and choose a strong new password.':step==='done'?'You can now sign in using your new password.':registering?'Verify your email before your account is created.':'Sign in to your orders, market plans and conversations.'}</p>
 {choosing?<div className="auth-role-choices"><Link to="/register/customer"><strong>I’m shopping</strong><span>Discover produce and plan pickups.</span><ArrowRight/></Link><Link to="/register/farmer"><strong>I’m a grower</strong><span>Apply for a stall and manage your harvest.</span><ArrowRight/></Link></div>:step==='done'?<Link className="button" to="/login" onClick={()=>{setStep('form');setError('')}}>Back to sign in</Link>:<form onSubmit={submit} className="auth-clean-form">
 {error&&<p className="auth-alert" role="alert">{error}</p>}
 {step==='form'&&registering&&<><div className="auth-field-pair"><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required minLength={7} maxLength={20}/></label></div>{farmer&&<label>Farm or business name<input name="businessName" autoComplete="organization" required minLength={2} maxLength={100}/></label>}</>}
 {(step==='form'||step==='forgot')&&<label>Email address<input type="email" name="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}
 {step==='form'&&registering&&<label>{farmer?'Farm / business address':'Address'}<input name="address" autoComplete="street-address" required minLength={5} maxLength={250}/></label>}
 {(step==='verify'||step==='reset')&&<label>Email verification code<input className="auth-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label>}
 {(step==='form'||step==='reset')&&<PasswordField value={password} onChange={setPassword} strong={registering||step==='reset'}/>}
 {(step==='form'&&registering||step==='reset')&&<label>Confirm password<input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}
 {step==='form'&&!registering&&<button type="button" className="auth-text-action" onClick={()=>{setStep('forgot');setError('')}}>Forgot password?</button>}
 <button className="button auth-submit" disabled={busy}>{busy?'Please wait…':step==='verify'?'Verify email & continue':step==='forgot'?'Send reset code':step==='reset'?'Update password':registering?'Send verification code':'Sign in'}<ArrowRight size={18}/></button>
 {step==='verify'&&<><p className="auth-footnote"><Mail size={15}/> Check your spam folder too. Your code is never shown on this page.</p><button type="button" className="auth-text-action" onClick={()=>{setStep('form');setCode('');setError('')}}>Change details or request a new code</button></>}
 </form>}
 <p className="auth-switch">{registering?'Already have an account?':'New to Gather & Grow?'} <Link to={registering?'/login':'/register'} onClick={()=>{setStep('form');setError('');setCode('')}}>{registering?'Sign in':'Create an account'}</Link></p><p className="auth-footnote">Your account gives you access to your own workspace. Farmer selling access requires administrator approval.</p></div></main></div>
}
