import {useEffect,useState} from 'react';
import {fetchFarmerProfileApi,updateFarmerProfileApi} from '../data/api';
import {gateway} from '../data/gateway';
import {LocationPicker} from '../components/LocationPicker';
export function FarmerSettings({page}:{page:string}){
 const [profile,setProfile]=useState<any>(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{void fetchFarmerProfileApi().then(setProfile).catch(e=>setError(e.message))},[]);
 function change(k:string,v:unknown){setProfile((p:any)=>({...p,[k]:v}));setSaved(false)}
 return <div className="container section narrow"><h1>{page==='markets'?'Your farm location':'Your stall profile'}</h1><p>Keep your public details and saved map pin accurate.</p>{error&&<p role="alert" className="error">{error}</p>}{profile?<form className="paper-panel application-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSaved(false);try{await updateFarmerProfileApi({businessName:profile.businessName,contactPerson:profile.contactPerson,bio:profile.bio,phone:profile.phone,address:profile.address,stallNumber:profile.stallNumber,stallCoordinates:profile.stallCoordinates});await gateway.refresh();setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Could not save changes.')}finally{setBusy(false)}}}>
 {page==='profile'?<>{[['businessName','Farm / business name'],['contactPerson','Contact person'],['phone','Phone']].map(([key,label])=><label key={key}>{label}<input required minLength={key==='phone'?7:2} value={profile[key]||''} onChange={e=>change(key,e.target.value)}/></label>)}<label>Farm story<textarea rows={5} maxLength={1000} value={profile.bio||''} onChange={e=>change('bio',e.target.value)}/></label><details><summary>Farm address and map pin</summary><p>Your growing location, not the market where customers collect orders.</p><label>Farm address<textarea required minLength={5} value={profile.address||''} onChange={e=>change('address',e.target.value)}/></label><LocationPicker value={profile.stallCoordinates||undefined} country={profile.countryCode} query={[profile.address,profile.city,profile.countryName].filter(Boolean).join(', ')} onChange={v=>change('stallCoordinates',v)}/></details></>:<><p>{profile.city}, {profile.countryName}</p><label>Farm address<textarea required minLength={5} value={profile.address||''} onChange={e=>change('address',e.target.value)}/></label><label>Stall number<input maxLength={50} value={profile.stallNumber||''} onChange={e=>change('stallNumber',e.target.value)}/></label><LocationPicker value={profile.stallCoordinates||undefined} country={profile.countryCode} query={[profile.address,profile.city,profile.countryName].filter(Boolean).join(', ')} onChange={v=>change('stallCoordinates',v)}/><p className="small">For a change of city or participating venue, open a support ticket so the administrator can review it.</p></>}
 <button className="button" disabled={busy}>{busy?'Saving…':'Save changes'}</button>{saved&&<p role="status">Your changes were saved to your farmer profile.</p>}</form>:<p>Loading your profile…</p>}</div>
}
