import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getFarmerOnboardingApi,saveFarmerOnboardingStepApi,submitFarmerOnboardingApi} from '../data/api';
import {gateway} from '../data/gateway';
import {useMarket} from '../components/ui';
import {countryOptions,countryName} from '../data/visitor';
import {LocationPicker} from '../components/LocationPicker';
export function FarmerApplication(){
 const s=useMarket();const [application,setApplication]=useState<any>(null),[steps,setSteps]=useState<Record<string,any>>({}),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const keys=['','account','location','profile','markets','review'];
 async function load(){try{const a=await getFarmerOnboardingApi();setApplication(a);setSteps(a.stepData)}catch(e){setError(e instanceof Error?e.message:'Application could not be loaded.')}}
 useEffect(()=>{void load();const timer=setInterval(()=>{void getFarmerOnboardingApi().then(a=>{setApplication(a);if(a.approvalStatus==='approved')void gateway.refresh()}).catch(()=>{})},15000);return()=>clearInterval(timer)},[]);
 const key=`step${step}_${keys[step]}`,data=steps[key]||{},location=steps.step2_location||{},profile=steps.step3_profile||{},account=steps.step1_account||{};
 const venues=s.markets.filter(m=>m.active&&m.countryCode===location.countryCode&&m.city?.trim().toLowerCase()===location.city?.trim().toLowerCase());
 function change(field:string,value:unknown){setSteps(prev=>({...prev,[key]:{...prev[key],[field]:value},...(step===2?{step4_markets:{requestedMarketIds:[]}}:{})}));setNotice('')}
 async function save(next:boolean){setBusy(true);setError('');try{await saveFarmerOnboardingStepApi(step===5?8:step,step===5?{agreedToTerms:data.agreedToTerms===true}:data);setNotice('Draft saved.');if(next)setStep(n=>Math.min(5,n+1))}catch(e){setError(e instanceof Error?e.message:'Could not save. Your entries remain here.')}finally{setBusy(false)}}
 async function submit(){setBusy(true);setError('');try{await saveFarmerOnboardingStepApi(8,{agreedToTerms:data.agreedToTerms===true});const a=await submitFarmerOnboardingApi();setApplication(a);await gateway.refresh()}catch(e){setError(e instanceof Error?e.message:'Submission failed. Please try again.')}finally{setBusy(false)}}
 if(!application)return <div className="container section"><h1>Farmer application</h1><p role="status">{error||'Loading your saved application…'}</p><button onClick={load}>Retry</button></div>;
 const locked=application.status==='submitted'||['approved','suspended'].includes(application.approvalStatus);
 const labels=['Identity','Location','Farm profile','Market venues','Review'];
 return <div className="farmer-workbench container application-workspace"><header className="fw-header"><div><p className="eyebrow">Weekly planner · account setup</p><h1>{locked?(application.approvalStatus==='approved'?'Your farm is approved.':application.approvalStatus==='suspended'?'Your account is suspended.':'Your application is under review.'):'Prepare your farm for market day.'}</h1><p>Complete your details, choose a local venue and submit for approval. Selling tools unlock after approval.</p></div><Link className="button secondary" to="/farmer/support">Contact support</Link></header>
 {application.adminNotes&&<aside className="notice"><strong>Administrator’s message</strong><p>{application.adminNotes}</p></aside>}
 {locked?<section className="paper-panel"><h2>{profile.businessName||'Your submitted application'}</h2><p>{account.contactPerson} · {location.city}, {countryName(location.countryCode||'')}</p><p>{profile.bio}</p><p>{application.approvalStatus==='approved'?'Open your weekly planner to manage stock and pickups.':'Your saved details are protected while the administrator reviews them. This page checks for a decision automatically.'}</p><button className="button" onClick={async()=>{await load();await gateway.refresh()}}>Refresh status</button></section>:<><nav className="application-steps" aria-label="Application steps">{labels.map((label,i)=><button key={label} type="button" aria-current={step===i+1?'step':undefined} onClick={()=>{setStep(i+1);setError('')}}>{i+1}. {label}</button>)}</nav><form className="paper-panel application-form" onSubmit={e=>{e.preventDefault();void(step===5?submit():save(true))}}><h2>{labels[step-1]}</h2>
 {step===1&&<>{[['contactPerson','Contact person'],['phone','Phone'],['secondaryPhone','Secondary phone (optional)']].map(([name,label])=><label key={name}>{label}<input required={name!=='secondaryPhone'} minLength={name==='contactPerson'?2:5} value={data[name]||''} onChange={e=>change(name,e.target.value)}/></label>)}</>}
 {step===2&&<><label>Country<select required value={data.countryCode||''} onChange={e=>{change('countryCode',e.target.value);change('countryName',countryName(e.target.value))}}><option value="">Choose your country</option>{countryOptions('en').map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label>{[['region','State / province / region'],['city','City'],['address','Farm address']].map(([name,label])=><label key={name}>{label}<input required minLength={name==='address'?5:2} value={data[name]||''} onChange={e=>change(name,e.target.value)}/></label>)}<LocationPicker value={data.coordinates} country={data.countryCode} query={[data.address,data.city,data.countryName].filter(Boolean).join(', ')} onChange={v=>change('coordinates',v)}/></>}
 {step===3&&<><label>Business name<input required minLength={2} value={data.businessName||''} onChange={e=>change('businessName',e.target.value)}/></label><label>About your farm<textarea required minLength={10} maxLength={1000} rows={5} value={data.bio||''} onChange={e=>change('bio',e.target.value)}/></label><label>Growing practices (your own description)<input value={(data.farmingPractices||[]).join(', ')} onChange={e=>change('farmingPractices',e.target.value.split(',').map(v=>v.trim()))}/></label></>}
 {step===4&&<><p>Registered venues in {location.city||'your selected city'}, {countryName(location.countryCode||'')}. Change location in step 2 if needed.</p>{venues.length?<label>Market venue<select required value={data.requestedMarketIds?.[0]||''} onChange={e=>change('requestedMarketIds',[e.target.value])}><option value="">Choose a venue</option>{venues.map(m=><option key={m.id} value={m.id}>{m.name} · {m.address}</option>)}</select></label>:<div className="notice"><h3>No registered venue here yet</h3><p>We have not listed a market in this city. Your draft is saved; ask support to add a venue before submitting.</p><Link to="/farmer/support">Request a venue through support</Link></div>}</>}
 {step===5&&<><dl className="definition-list"><dt>Farmer</dt><dd>{account.contactPerson} · {account.phone}</dd><dt>Farm</dt><dd>{profile.businessName}<p>{profile.bio}</p></dd><dt>Address</dt><dd>{location.address}, {location.city}, {location.countryName}</dd><dt>Venue</dt><dd>{s.markets.find(m=>m.id===steps.step4_markets?.requestedMarketIds?.[0])?.name||'No venue selected'}</dd></dl>{location.coordinates&&<LocationPicker value={location.coordinates} readOnly/>}<label className="check"><input type="checkbox" required checked={data.agreedToTerms||false} onChange={e=>change('agreedToTerms',e.target.checked)}/>I confirm these details are accurate and agree to the seller terms described in Help.</label><Link to="/help" target="_blank">Read how selling and pickup work</Link></>}
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="actions">{step>1&&<button type="button" className="button secondary" onClick={()=>setStep(n=>n-1)}>Back</button>}<button className="button" disabled={busy||(step===4&&!venues.length)}>{busy?'Saving…':step===5?'Submit application':'Save and continue'}</button>{step<5&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void save(false)}>Save draft</button>}</div></form></>}
 </div>
}
