import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {MapPin,CalendarDays,ArrowUpRight,Store} from 'lucide-react';
import {useMarket} from '../components/ui';
import {fetchFarmerProfileApi,marketParticipationApi,type MarketJoinRequest} from '../data/api';
import {LocationPicker} from '../components/LocationPicker';
import {gateway} from '../data/gateway';
export function FarmerMarkets(){
 const s=useMarket();const [profile,setProfile]=useState<any>(null),[requests,setRequests]=useState<MarketJoinRequest[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){const [p,r]=await Promise.all([fetchFarmerProfileApi(),marketParticipationApi.list()]);setProfile(p);setRequests(r)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const joined=s.markets.filter(m=>profile?.marketIds?.includes(m.id));
 const available=s.markets.filter(m=>m.active&&!profile?.marketIds?.includes(m.id)&&m.countryCode===profile?.countryCode&&m.city?.trim().toLowerCase()===profile?.city?.trim().toLowerCase());
 async function apply(id:string){setBusy(id);setError('');try{setRequests(await marketParticipationApi.apply(id))}catch(e){setError(e instanceof Error?e.message:'Could not send request.')}finally{setBusy('')}}
 return <div className="farmer-workbench container"><div className="fw-header"><div><span className="fw-status-chip accepted"><Store size={14}/> Market participation</span><h1>Your markets & pickup venues</h1><p className="fw-header-sub">These are the markets where customers collect your orders. Your farm address is managed separately in your stall profile.</p></div><Link className="button secondary" to="/farmer/profile">Edit farm profile</Link></div>{error&&<p role="alert" className="error">{error}</p>}<ol className="venue-journey"><li><strong>1. Join a venue</strong><span>Select a local market. An administrator reviews your request.</span></li><li><strong>2. Publish dated stock</strong><span>Choose the market day and the quantity you can actually bring.</span></li><li><strong>3. Open pickup windows</strong><span>Customers reserve and collect at that market. Payment is at pickup.</span></li></ol>{!profile?<p role="status">Loading your market participation…</p>:<><section className="venue-section"><h2>Your approved venues</h2>{joined.length?joined.map(m=><article className="venue-record" key={m.id}><div><span className="fw-status-chip accepted">{m.active?'Approved venue':'Venue inactive'}</span><h3>{m.name}</h3><p><MapPin size={16}/> {m.address} · {m.city}</p><p><CalendarDays size={16}/> {m.dayNames?.join(', ')||m.day} · {m.hours}</p><div className="actions"><Link className="button" to="/farmer/stock">Plan dated stock</Link><Link className="button secondary" to="/farmer/pickup-windows">Set pickup windows</Link><Link to={`/markets/${m.id}`}>View market <ArrowUpRight size={15}/></Link></div></div>{m.coordinates&&<LocationPicker value={m.coordinates} readOnly/>}</article>):<p className="paper-panel">You have no approved market venues yet. Request one below before publishing stock or pickup windows.</p>}</section><section className="venue-section"><h2>Request another venue</h2><p>Registered markets in {profile.city||'your city'}, {profile.countryName||profile.countryCode}. Joining is subject to administrator approval.</p>{available.length?available.map(m=>{const r=requests.find(r=>r.marketId===m.id);return <article className="venue-option" key={m.id}><div><h3>{m.name}</h3><p>{m.address}</p>{r&&<p role="status">{r.status==='pending'?'Request sent — awaiting administrator review.':r.status==='rejected'?`Returned: ${r.reason}`:'Approved'}</p>}</div><button className="button secondary" disabled={!!busy||r?.status==='pending'} onClick={()=>void apply(m.id)}>{busy===m.id?'Sending…':r?.status==='pending'?'Awaiting review':r?.status==='rejected'?'Request again':'Request to join'}</button></article>}):<p>No additional registered venues match your city. <Link to="/farmer/support">Contact support about a venue or location change.</Link></p>}</section></>}</div>
}
export function MarketRequestReview({farmerId}:{farmerId:string}){
 const [rows,setRows]=useState<MarketJoinRequest[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[reasons,setReasons]=useState<Record<string,string>>({});
 useEffect(()=>{void marketParticipationApi.list(farmerId).then(setRows).catch(e=>setError(e.message))},[farmerId]);
 async function decide(marketId:string,status:'approved'|'rejected'){if(status==='rejected'&&!reasons[marketId]?.trim()){setError('Explain why this venue request is being returned.');return}if(!window.confirm(`${status==='approved'?'Approve':'Return'} this venue request?`))return;setBusy(marketId);setError('');try{setRows(await marketParticipationApi.decide(farmerId,marketId,status,reasons[marketId]||''));await gateway.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save decision.')}finally{setBusy('')}}
 return <section className="paper-panel"><h2>Market participation requests</h2><p>Approving a venue allows this farmer to plan stock and customer pickups there.</p>{error&&<p role="alert" className="error">{error}</p>}{!rows.length?<p>No additional venue requests.</p>:rows.map(r=><article className="venue-option" key={r.marketId}><div><h3>{r.marketName}</h3><p>{r.status}{r.reason?` — ${r.reason}`:''}</p>{r.status==='pending'&&<><label>Message to farmer<textarea maxLength={500} value={reasons[r.marketId]||''} onChange={e=>setReasons({...reasons,[r.marketId]:e.target.value})}/></label><div className="actions"><button className="button" disabled={!!busy} onClick={()=>void decide(r.marketId,'approved')}>Approve venue</button><button className="button secondary" disabled={!!busy} onClick={()=>void decide(r.marketId,'rejected')}>Return request</button></div></>}</div></article>)}</section>
}
