import {useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useMarket} from '../components/ui';
import {LocationPicker} from '../components/LocationPicker';
import type {Point} from '../components/LocationPicker';
import {countryName,countryOptions} from '../data/visitor';
import {createAdminMarketApi,updateAdminMarketApi} from '../data/api';
import {gateway} from '../data/gateway';
export function VenueEditor(){
 const s=useMarket(),{marketId}=useParams(),navigate=useNavigate(),m=s.markets.find(m=>m.id===marketId);
 const [point,setPoint]=useState<Point|undefined>(m?.coordinates),[country,setCountry]=useState(m?.countryCode||''),[city,setCity]=useState(m?.city||''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[days,setDays]=useState<number[]>(m?.operatingDays||[]);
 return <div className="container section narrow"><Link to="/admin/markets">Back to markets</Link><h1>{m?'Edit '+m.name:'Add a market venue'}</h1><p>Set its real address, map pin and local opening schedule.</p><form className="paper-panel application-form" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(!point){setError('Select the venue on the map.');return}if(!days.length){setError('Select at least one operating day.');return}if(String(d.get('close'))<=String(d.get('open'))){setError('Closing time must be after opening time.');return}try{new Intl.DateTimeFormat('en',{timeZone:String(d.get('timezone'))})}catch{setError('Enter a valid IANA timezone, such as Europe/London.');return}setBusy(true);setError('');try{const payload={name:String(d.get('name')),countryCode:country,countryName:countryName(country),city,region:String(d.get('region')),locality:String(d.get('locality')),address:String(d.get('address')),currency:String(d.get('currency')).toUpperCase(),timezone:String(d.get('timezone')),coordinates:point,operatingDays:days,operatingHours:{open:String(d.get('open')),close:String(d.get('close'))},mapProvider:'osm'};if(m)await updateAdminMarketApi(m.id,payload);else await createAdminMarketApi(payload);await gateway.refresh();navigate('/admin/markets')}catch(e){setError(e instanceof Error?e.message:'Market could not be saved.')}finally{setBusy(false)}}}>
 <label>Venue name<input name="name" required minLength={2} defaultValue={m?.name}/></label><label>Country<select required value={country} onChange={e=>setCountry(e.target.value)}><option value="">Select country</option>{countryOptions('en').map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><div className="two-col"><label>Region<input name="region" minLength={2} required defaultValue={m?.region}/></label><label>City<input required minLength={2} value={city} onChange={e=>setCity(e.target.value)}/></label></div><label>Neighbourhood<input name="locality" defaultValue={m?.area}/></label><label>Full address<textarea name="address" required minLength={5} defaultValue={m?.address}/></label><LocationPicker value={point} onChange={setPoint} country={country} query={[city,countryName(country)].filter(Boolean).join(', ')}/><fieldset><legend>Operating days</legend><div className="actions">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><label key={d}><input type="checkbox" checked={days.includes(i)} onChange={e=>setDays(e.target.checked?[...days,i]:days.filter(n=>n!==i))}/>{d}</label>)}</div></fieldset><div className="two-col"><label>Opens (local time)<input type="time" name="open" required defaultValue={m?.open||'08:00'}/></label><label>Closes (local time)<input type="time" name="close" required defaultValue={m?.close||'13:00'}/></label><label>IANA timezone<input name="timezone" required defaultValue={m?.timeZone||''} placeholder="Europe/London"/></label><label>Currency code<input name="currency" required pattern="[A-Za-z]{3}" defaultValue={m?.currency||''} placeholder="GBP"/></label></div>{error&&<p role="alert" className="error">{error}</p>}<button className="button" disabled={busy}>{busy?'Saving…':'Save venue'}</button></form></div>
}
