import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {searchLocationsApi} from '../data/api';
export type Point={latitude:number;longitude:number};
export function LocationPicker({value,onChange,readOnly=false,country='',query=''}:{value?:Point;onChange?:(p:Point)=>void;readOnly?:boolean;country?:string;query?:string}){
 const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),pin=useRef<L.CircleMarker|null>(null),callback=useRef(onChange);
 callback.current=onChange;
 const [search,setSearch]=useState(query),[results,setResults]=useState<{label:string;latitude:number;longitude:number}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setSearch(query)},[query]);
 useEffect(()=>{if(!host.current)return;const m=L.map(host.current,{scrollWheelZoom:false}).setView(value?[value.latitude,value.longitude]:[22,0],value?13:2);map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);if(!readOnly)m.on('click',e=>callback.current?.({latitude:e.latlng.lat,longitude:e.latlng.wrap().lng}));const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(host.current);return()=>{observer.disconnect();m.remove();map.current=null}},[readOnly]);
 useEffect(()=>{const m=map.current;if(!m)return;if(pin.current){pin.current.remove();pin.current=null}if(value){pin.current=L.circleMarker([value.latitude,value.longitude],{radius:9,color:'#fff',weight:3,fillColor:'#183b2b',fillOpacity:1}).addTo(m);m.setView([value.latitude,value.longitude],Math.max(m.getZoom(),12))}},[value?.latitude,value?.longitude]);
 return <section className="location-picker" aria-label="Map location">{!readOnly&&<><div className="map-search"><input aria-label="Search map address" value={search} onChange={e=>setSearch(e.target.value)} placeholder="City, street or address"/><button type="button" className="button secondary" disabled={busy||search.trim().length<3} onClick={async()=>{setBusy(true);setError('');try{const found=await searchLocationsApi(search,country);setResults(found);if(!found.length)setError('No matching address. Zoom and select a point on the map.')}catch{setError('Address search unavailable. You can still select a point on the map.')}finally{setBusy(false)}}}>{busy?'Searching…':'Find on map'}</button></div>{results.map((r,i)=><button type="button" className="map-result" key={i} onClick={()=>{onChange?.({latitude:r.latitude,longitude:r.longitude});setResults([])}}>{r.label}</button>)}<p className="small">Search, then click the map to place your exact pin. Scroll zoom is off so the page stays easy to use.</p></>}{error&&<p role="status">{error}</p>}<div ref={host} style={{height:320,width:'100%',zIndex:0}}/>{value?<p className="small">Selected: {value.latitude.toFixed(5)}, {value.longitude.toFixed(5)} · <a href={`https://www.google.com/maps/search/?api=1&query=${value.latitude},${value.longitude}`} target="_blank" rel="noreferrer">Open directions</a></p>:<p className="small">No pin selected yet.</p>}{!readOnly&&<div className="two-col">{(['latitude','longitude'] as const).map(k=><label key={k}>{k}<input aria-label={k} type="number" step="any" min={k==='latitude'?-90:-180} max={k==='latitude'?90:180} value={value?.[k]??''} onChange={e=>{if(e.target.value&&e.target.validity.valid)onChange?.({...value??{latitude:0,longitude:0},[k]:Number(e.target.value)})}}/></label>)}</div>}</section>
}
