import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {Leaf,X,ArrowUp,ArrowUpRight,MapPin} from 'lucide-react';
import {askPublicGuideApi} from '../data/api';
import {useVisitor} from '../data/visitor-context';
import {ChatText} from './ChatText';
import './assistant-experience.css';
type Answer=Awaited<ReturnType<typeof askPublicGuideApi>>&{question:string};
export function PublicGuide(){const [open,setOpen]=useState(false);return <><button className="market-guide-launcher" onClick={()=>setOpen(true)}><Leaf size={19}/><span>Ask Market Guide</span></button>{open&&<GuidePanel onClose={()=>setOpen(false)}/>}</>}
function GuidePanel({onClose}:{onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),end=useRef<HTMLDivElement>(null);const {visitor}=useVisitor();const [question,setQuestion]=useState(''),[answers,setAnswers]=useState<Answer[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[answers,busy]);
 async function ask(q:string){if(busy||!q.trim())return;setBusy(true);setError('');try{const result=await askPublicGuideApi(q,visitor.country||'',visitor.city||'');setAnswers(a=>[...a,{...result,question:q}]);setQuestion('')}catch(e){setError(e instanceof Error?e.message:'The guide is unavailable. You can still browse the market.')}finally{setBusy(false)}}
 function send(e:FormEvent){e.preventDefault();void ask(question)}
 return <dialog ref={dialog} className="market-guide-panel" aria-labelledby="guide-title" onCancel={onClose}><header><div className="guide-emblem"><Leaf size={23}/></div><div><h2 id="guide-title">Market Guide</h2><p>Your way around Gather & Grow</p></div><button className="icon-button" aria-label="Close Market Guide" onClick={onClose}><X size={20}/></button></header><div className="guide-location"><MapPin size={14}/>{visitor.city||'All published locations'}<span>Public information only</span></div><div className="guide-conversation"><div className="guide-welcome"><h3>Find your next good thing.</h3><p>Ask about produce, growers, markets or how pickup works. I can help you explore, but cannot change accounts or orders.</p></div>{!answers.length&&<div className="guide-prompts">{['Which markets can I visit?','Show me growers','Find fresh produce','How do pickup and payment work?'].map(q=><button key={q} disabled={busy} onClick={()=>void ask(q)}>{q}<ArrowUpRight size={15}/></button>)}</div>}{answers.map((a,i)=><article className="guide-turn" key={i}><p className="guide-question">{a.question}</p><ChatText text={a.reply}/><div className="guide-results">{a.sources.filter(x=>/^\/(markets|farmers|products)\/[a-f0-9]{24}$/.test(x.href)).map(x=><Link key={x.href} to={x.href} onClick={onClose}><div><strong>{x.title}</strong><span>{x.detail}</span></div><ArrowUpRight size={16}/></Link>)}</div><small>{a.engine}</small></article>)}{busy&&<p role="status" className="guide-thinking">Checking the public catalogue…</p>}{error&&<p role="alert" className="auth-alert">{error}</p>}<div ref={end}/></div><form onSubmit={send} className="guide-composer"><label className="visually-hidden" htmlFor="guide-question">Ask Market Guide</label><textarea rows={2} id="guide-question" autoComplete="off" placeholder="Ask about markets, growers or pickup…" maxLength={1500} value={question} onChange={e=>setQuestion(e.target.value)}/><button disabled={busy||question.trim().length<2} aria-label="Send question"><ArrowUp size={20}/></button></form><p className="guide-policy">Stock and pickup availability are checked again when you reserve.</p></dialog>
}
