import {describe,it,expect,vi,beforeEach} from 'vitest';
const m=vi.hoisted(()=>({pending:{findOne:vi.fn(),createIndex:vi.fn(),insertOne:vi.fn(),deleteOne:vi.fn(),updateOne:vi.fn(),findOneAndDelete:vi.fn()},users:{findOne:vi.fn(),updateOne:vi.fn()},send:vi.fn(),customer:vi.fn(),farmer:vi.fn()}));
vi.mock('../../src/config/db.js',()=>({getDB:()=>({collection:n=>n==='users'?m.users:m.pending})}));
vi.mock('../../src/utils/token.js',()=>({hashPassword:async()=> 'hashed-password'}));
vi.mock('../../src/services/email.service.js',()=>({sendRegistrationOtpEmail:m.send}));
vi.mock('../../src/services/auth.service.js',()=>({registerCustomerService:m.customer,registerFarmerService:m.farmer}));
import {beginRegistration,finishRegistration} from '../../src/services/registration.service.js';
import {strongPasswordSchema} from '../../src/validation/auth.schema.js';
const data={email:'registration@example.test',name:'Test Person',password:'StrongPassword1!',phone:'123456789',address:'Test address'};
beforeEach(()=>{vi.resetAllMocks();m.users.findOne.mockResolvedValue(null);m.pending.findOne.mockResolvedValue(null);m.customer.mockResolvedValue({token:'test',user:{role:'customer'}});m.farmer.mockResolvedValue({token:'test',user:{role:'farmer'}})});
async function challenge(role='customer'){const result=await beginRegistration(data,role);const record=m.pending.insertOne.mock.calls[0][0];const code=m.send.mock.calls[0][1];m.pending.findOne.mockResolvedValue(record);m.pending.findOneAndDelete.mockResolvedValueOnce(record).mockResolvedValue(null);return {result,record,code}}
describe('Registration email verification',()=>{
 it('stores neither raw password nor OTP and creates no account before verification',async()=>{const {result,record,code}=await challenge();expect(result).toEqual({challengeId:record._id,email:data.email,verificationRequired:true});expect(record.data.password).toBeUndefined();expect(record.passwordHash).toBe('hashed-password');expect(record.codeHash).not.toBe(code);expect(m.customer).not.toHaveBeenCalled();expect(m.farmer).not.toHaveBeenCalled()});
 it('creates an account only after a correct code and rejects replay',async()=>{const {result,code}=await challenge();await expect(finishRegistration(result.challengeId,'000000')).rejects.toThrow('Incorrect');expect(m.customer).not.toHaveBeenCalled();await finishRegistration(result.challengeId,code);expect(m.customer).toHaveBeenCalledWith(expect.not.objectContaining({password:expect.anything()}),'hashed-password');expect(m.users.updateOne).toHaveBeenCalled();await expect(finishRegistration(result.challengeId,code)).rejects.toMatchObject({statusCode:409})});
 it('keeps farmer registration distinct',async()=>{const {result,code}=await challenge('farmer');await finishRegistration(result.challengeId,code);expect(m.farmer).toHaveBeenCalledOnce();expect(m.customer).not.toHaveBeenCalled()});
 it('rejects expired challenges and too many attempts',async()=>{const {result,record,code}=await challenge();record.expiresAt=new Date(0);await expect(finishRegistration(result.challengeId,code)).rejects.toThrow('expired');record.expiresAt=new Date(Date.now()+10000);record.attempts=5;await expect(finishRegistration(result.challengeId,code)).rejects.toMatchObject({statusCode:429});expect(m.customer).not.toHaveBeenCalled()});
 it('fails closed and removes challenge when email delivery fails',async()=>{m.send.mockRejectedValue(new Error('Email unavailable'));await expect(beginRegistration(data,'customer')).rejects.toThrow('Email unavailable');expect(m.pending.deleteOne).toHaveBeenCalledOnce();expect(m.customer).not.toHaveBeenCalled()});
 it('rejects registered emails and throttles resends',async()=>{m.users.findOne.mockResolvedValue({});await expect(beginRegistration(data,'customer')).rejects.toMatchObject({statusCode:409});m.users.findOne.mockResolvedValue(null);m.pending.findOne.mockResolvedValue({});await expect(beginRegistration(data,'customer')).rejects.toMatchObject({statusCode:429})});
 it('enforces strong passwords including the bcrypt byte limit',()=>{for(const password of ['short','Longbutnonumber!','alllowercase123!','StrongPassword1!'+'é'.repeat(40)])expect(strongPasswordSchema.safeParse(password).success).toBe(false);expect(strongPasswordSchema.safeParse(data.password).success).toBe(true)});
});
